version: '3.4'

services:

  nginx:
    image: nginx:1.15-alpine
    ports:
      - "8080:80"
    volumes:
      - ./etc/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - php

  php:
    build:
      context: ./etc/dev/php/
    ports:
      - "2323:22"
    volumes:
      - .:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=api
    volumes:
      - db_data:/var/lib/mysql
    entrypoint:
      sh -c "echo 'CREATE DATABASE IF NOT EXISTS my_theresa; CREATE DATABASE IF NOT EXISTS my_theresa_test;' >
      /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
volumes:
  db_data:
